#!/bin/sh
echo "jmx-tester listening on port 9991"
java \
    -Dcom.sun.management.jmxremote.port=9991 \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -jar target/jmx-tester-1.0.0.jar
